name: Run Headless Chrome App

on:
  schedule:
    - cron: '32 13 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show timezone
        run: timedatectl 

      - name: Display current time before
        run: date

      - name: Set timezone to ET
        run: sudo timedatectl set-timezone America/New_York

      - name: Display current time
        run: date

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --verbose

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: node src/main.js
