name: Run Headless Chrome App

on:
  schedule:
    - cron: '32 9 * * *'  # Runs at 9:32 AM every day
    - cron: '30 11 * * *' # Runs at 11:30 AM every day
    - cron: '30 13 * * *' # Runs at 1:30 PM every day
    - cron: '30 15 * * *' # Runs at 3:30 PM every day
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install --verbose

      - name: Run script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: node src/main.js
